const OPERATIONS = {
    GREET_SHORT: "GREET_SHORT",
    GREET_LONG: "GREET_LONG",
    THANK_GENERIC: "THANK_GENERIC",
    THANK_POLITENESS: "THANK_POLITENESS",
    NOOP: "NOOP",
};

module.exports = OPERATIONS;