const OPERATIONS = {
    SCHOOLING: "SCHOOLING",
    CAREER: "CAREER",
    PERSONAL: "PERSONAL",
    PROJECTS: "PROJECTS",
    TRIVIA: "TRIVIA",
    SKILLS: "SKILLS",
    CONTACT: "CONTACT",
    TECHNOLOGIES: "TECHNOLOGIES",
    LANGUAGES: "LANGUAGES",
    NOOP: "NOOP",
};

module.exports = OPERATIONS;