module.exports = [
  "educação",
  "educaçao",
  "escolaridade",
  "carreira",
  "emprego",
  "trabalho",
  "histórico",
  "historico",
  "experiência",
  "experiencia",
  "empresa",
  "pessoal",
  "projeto",
  "github",
  "repositório",
  "repositorio",
  "curiosidade",
  "sobre você",
  "sobre voce",
  "habilidade",
  "skill",
  "contato",
  "tecnologia",
  "idioma",
  "inglês",
  "ingles",
  "quem é voce",
  "quem é voce",
  "quem e você",
  "quem e voce",
];
